---
- hosts: routers
  gather_facts: false
  connection: network_cli

  tasks:
  - name: update prefix-list {{ prefixlist_name }}
    vars:
      prefixlist_name: prefix-list-test-in
    import_role:
      name: ios-prefix-list

  - name: apply prefix-list {{ prefixlist_name }} on route-map {{ routemap_name }}
    vars:
      prefixlist_name: prefix-list-test-in
      routemap_name: route-map-test-in
    import_role:
      name: ios-route-map

  - name: update prefix-list {{ prefixlist_name }}
    vars:
      prefixlist_name: prefix-list-test-out 
    import_role:
      name: ios-prefix-list

  - name: apply prefix-list {{ prefixlist_name }} on route-map {{ routemap_name }}
    vars:
      prefixlist_name: prefix-list-test-out 
      routemap_name: route-map-test-out 
    import_role:
      name: ios-route-map


